### ISSUE TITLE
Embedded/Linked documents use forwardslash instead of backslash 

### ISSUE THREAD

**Issue by technotherion** [alberti42/obsidian-import-attachments-plus#1] opened 2024-07-07 20:20 UTC
Here are my current settings: 
![image](https://github.com/alberti42/obsidian-import-attachments-plus/assets/13829537/e509e000-5d7f-4715-8957-d54dd919261c)

I drag a sample image into my vault and choose these import settings. 
![image](https://github.com/alberti42/obsidian-import-attachments-plus/assets/13829537/ce14dbcd-763c-49b5-b9b5-b5e2779a759c)

The image was correctly placed under _resources/Untitled but the note says that the file can not be found. 
`![[_resources\Untitled\Mister_Puck_064-2024_07_07T15_18_21.png]]`

Upon switching these to backslashes, the image embeds properly. 

![image](https://github.com/alberti42/obsidian-import-attachments-plus/assets/13829537/c5b9d821-0ac3-487e-95c6-0c940eb69884)

**Comment by alberti42** [comment] 2024-07-08 08:36
Thanks a lot for the feedback. Today is a busy day. But the bug will 
certainly be fixed.

Are you running under Windows? I should do some more tests. In MacOS and 
Linux (where I did most of the tests), the backslash is not really used 
for files. I would expect Windows to use it. However, perhaps Obsidian 
expects forward slash instead. It kind of makes sense to keep 
compatibility across the Unix devices too.

**Comment by alberti42** [comment] 2024-07-08 16:16
Ok, I released a new version where now the links are imported correctly. However, I think this breaks other features since now the links are stored with forward slash, but then Obsidian needs internally the path with backslash to operate on the attachment.

I think it is straightforward how to fix it, but I don't have time until Thursday/Friday.

**Comment by alberti42** [comment] 2024-07-08 16:30
Honestly, I realized a few features are broken in Windows. I should have tested it better. I did only for MacOS and Linux. I will fix the bugs in the following days.

Meanwhile you can already use it to import attachment by moving them to the vault. This works as intended.

**Comment by technotherion** [comment] 2024-07-08 18:16
Hello, yes I should have specified, I'm using Windows 10!
I will let you know if I encounter any more windows-specific issues.

**Comment by alberti42** [comment] 2024-07-08 18:27
... well, there are issues with additional features that you may want to 
switch on, such as automatic renaming of the attachment folder if you 
rename the note, and other small things that may not work as intended 
now on the Windows version.

All these niuances will be fixed for sure.

**Comment by alberti42** [comment] 2024-07-30 18:26
Ok. I believe all the problems are now fixed with the new version I just released. I would be grateful if you could send a feedback.

**Comment by alberti42** [comment] 2024-08-03 23:32
I believe the issue is now solved. Feel free to open the ticket again if you find more problems on that.

**Closed** 2024-08-03 23:31 UTC
